version: '3.9'
services:
  synthea:
    image: hsdemo-sda/synthea:base
    init: true
    build:
      context: .
      dockerfile: Dockerfile.Synthea
    container_name: synthea
    restart: "no"
    volumes:
    - ./output:/output

  iris:
    image: hsdemo-sda/iris:base
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hsdemo-sda
    container_name: hsdemo-sda
    ports:
    - "8091:51773" 
    - "8092:52773"
    restart: "no"
    volumes:
    - ./output:/output
    - ./code:/code