version: '3.9'
services:
  synthea:
    image: intersystems/demo/synthea/app:latest
    init: true
    build:
      context: .
      dockerfile: Dockerfile.Synthea
    container_name: synthea
    restart: "no"
    volumes:
    - ./output:/output

  iris:
    image: intersystems/demo/synthea/iris:latest
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hsdemo-sda
    container_name: hsdemo-sda
    ports:
    - "8091:1972" 
    - "8092:52773"
    restart: "no"
    volumes:
    - ./output:/output
    - ./code:/code